name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: web-self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Down compose
      run: docker compose down

    - name: Build and up compose
      run: docker compose up -d --build aist-front
